### ISSUE TITLE
Network Connection Issue

### ISSUE THREAD

**Issue by gow2613** [niyankhadka/crypto-wallet-bruteforce#5]
Total Checked: 0 || Execution Per Time: 0 || Elapsed Time: 0
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: party thrive machine stuff wolf vapor luxury ensure sausage leg friend olive
Wallet Address: 0x3F8684d99dF91a46cC192761c37bc86EDf07c044
---->>> Checking Transaction(s) on bsc
xxxxxxxx No Transactions Found on bsc
---->>> Checking Transaction(s) on eth
xxxxxxxx No Transactions Found on eth
---->>> Checking Transaction(s) on polygon
xxxxxxxx No Transactions Found on polygon
Total Checked: 1 || Execution Per Time: 0:00:14.110000 || Elapsed Time: 0:00:14.110000
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: idle adjust mule cost reveal cargo sad jeans ethics sea blast parrot
Wallet Address: 0x0DF13Adb5f82B3d47EC213a051FdA68F9ceca0F5
---->>> Checking Transaction(s) on bsc
xxxxxxxx No Transactions Found on bsc
---->>> Checking Transaction(s) on eth
xxxxxxxx No Transactions Found on eth
---->>> Checking Transaction(s) on polygon
xxxxxxxx No Transactions Found on polygon
Total Checked: 2 || Execution Per Time: 0:00:14.015000 || Elapsed Time: 0:00:28.250000
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: embrace shiver lion math south nominee brush avocado toss script second donor
Wallet Address: 0x6dB1bf10793593e1b599b7eB765943D48676Dd31
---->>> Checking Transaction(s) on bsc
xxxxxxxx No Transactions Found on bsc
---->>> Checking Transaction(s) on eth
xxxxxxxx No Transactions Found on eth
---->>> Checking Transaction(s) on polygon
xxxxxxxx No Transactions Found on polygon
Total Checked: 3 || Execution Per Time: 0:00:13.594000 || Elapsed Time: 0:00:41.860000
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: garden suit century flight soccer rubber because weapon memory device major trouble
Wallet Address: 0x8c906121c70Ea2a045Ef826F5FafaFD638eb51ea
---->>> Checking Transaction(s) on bsc
xxxxxxxx No Transactions Found on bsc
---->>> Checking Transaction(s) on eth
xxxxxxxx No Transactions Found on eth
---->>> Checking Transaction(s) on polygon
xxxxxxxx No Transactions Found on polygon
Total Checked: 4 || Execution Per Time: 0:00:12.235000 || Elapsed Time: 0:00:54.157000
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: appear live doll boost hope loud bulb reunion confirm purchase curtain answer
Wallet Address: 0x57E81efD6C59E867F1a839a5318ce7329B872842
---->>> Checking Transaction(s) on bsc
xxxxxxxx No Transactions Found on bsc
---->>> Checking Transaction(s) on eth
xxxxxxxx No Transactions Found on eth
---->>> Checking Transaction(s) on polygon
xxxxxxxx No Transactions Found on polygon
Total Checked: 5 || Execution Per Time: 0:00:14.172000 || Elapsed Time: 0:01:08.391000
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: shop naive warfare kid attitude celery suspect impact task below rack jar
Wallet Address: 0xdC434A0A629aAbAc10a1B15C0cc841E040859eD7
---->>> Checking Transaction(s) on bsc
xxxxxxxx No Transactions Found on bsc
---->>> Checking Transaction(s) on eth
xxxxxxxx No Transactions Found on eth
---->>> Checking Transaction(s) on polygon
xxxxxxxx No Transactions Found on polygon
Total Checked: 6 || Execution Per Time: 0:00:20.031000 || Elapsed Time: 0:01:28.438000
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: hood rabbit minor produce exact print movie ignore silver blue evolve slam
Wallet Address: 0x6188698C5a94925b799Cabc568517894C63301B1
---->>> Checking Transaction(s) on bsc
xxxxxxxx No Transactions Found on bsc
---->>> Checking Transaction(s) on eth
xxxxxxxx No Transactions Found on eth
---->>> Checking Transaction(s) on polygon
xxxxxxxx No Transactions Found on polygon
Total Checked: 7 || Execution Per Time: 0:00:15.875000 || Elapsed Time: 0:01:44.610000
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: tongue borrow bag crumble donor wedding evoke similar decorate copy menu bundle
Wallet Address: 0x1256711FA11b1356DF587DA4fEFE57F0C0695E38
---->>> Checking Transaction(s) on bsc
xxxxxxxx No Transactions Found on bsc
---->>> Checking Transaction(s) on eth
xxxxxxxx No Transactions Found on eth
Traceback (most recent call last):
  File "C:\Users\gowth\crypto-wallet-bruteforce\Python\run.py", line 207, in <module>
    main()
  File "C:\Users\gowth\crypto-wallet-bruteforce\Python\run.py", line 161, in main
    wallet_trnx_status = req_trnx( mainnet, bip44_hdwallet.address() )
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\crypto-wallet-bruteforce\Python\run.py", line 70, in req_trnx
    if check_connection() is True:
       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\crypto-wallet-bruteforce\Python\run.py", line 20, in check_connection
    requests.get( url, timeout = 10 )
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\gowth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\util\ssl_.py", line 446, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
KeyboardInterrupt

**Comment by niyankhadka** [comment]
Hi,
I think there was connection issue when I checked your console output. Sometimes, due to api request delay or limitations, wallet_trnx_status = req_trnx( mainnet, bip44_hdwallet.address() ) this will create an issue. 

if check_connection() is True: 
on this part, i think internet connection was lost, so can be creating issue on api request. 

As, i will be working on next version with enhancement of the code, will try to sort out the issue on newer version. 

Thank you for addressing the issue.

**Comment by niyankhadka** [comment]
Since there is no response at all, i will be closing this issue for now. Feel happy to raise the issue if you face any kind of problems.
